export const userData = [
  { id: 1, username: 'Linn', is_active: false },
  { id: 2, username: 'Crawford', is_active: true },
  { id: 3, username: 'Grove', is_active: false },
  { id: 4, username: 'Alfonso', is_active: true },
  { id: 5, username: 'Catlaina', is_active: true },
  { id: 6, username: 'Coralie', is_active: false },
  { id: 7, username: 'Louis', is_active: false },
  { id: 8, username: 'Nerti', is_active: true },
  { id: 9, username: 'Elinor', is_active: true },
  { id: 10, username: 'Gayle', is_active: false },
  { id: 11, username: 'Laryssa', is_active: false },
  { id: 12, username: 'Graham', is_active: false },
  { id: 13, username: 'Marcello', is_active: false },
  { id: 14, username: 'Caldwell', is_active: true },
  { id: 15, username: 'Benoite', is_active: false },
  { id: 16, username: 'Kathryne', is_active: false },
  { id: 17, username: 'Benson', is_active: false },
  { id: 18, username: 'Adrianne', is_active: false },
  { id: 19, username: 'Cristionna', is_active: false },
  { id: 20, username: 'Griff', is_active: false },
];
