export const userData = [
  { id: 1, username: 'Linn', status: 0 },
  { id: 2, username: 'Crawford', status: 1 },
  { id: 3, username: 'Grove', status: 0 },
  { id: 4, username: 'Alfonso', status: 1 },
  { id: 5, username: 'Catlaina', status: 1 },
  { id: 6, username: 'Coralie', status: 0 },
  { id: 7, username: 'Louis', status: 0 },
  { id: 8, username: 'Nerti', status: 1 },
  { id: 9, username: 'Elinor', status: 1 },
  { id: 10, username: 'Gayle', status: 0 },
  { id: 11, username: 'Laryssa', status: 0 },
  { id: 12, username: 'Graham', status: 0 },
  { id: 13, username: 'Marcello', status: 0 },
  { id: 14, username: 'Caldwell', status: 1 },
  { id: 15, username: 'Benoite', status: 0 },
  { id: 16, username: 'Kathryne', status: 0 },
  { id: 17, username: 'Benson', status: 0 },
  { id: 18, username: 'Adrianne', status: 0 },
  { id: 19, username: 'Cristionna', status: 0 },
  { id: 20, username: 'Griff', status: 0 },
];
