export const userData = [
  { id: 1, username: "Linn", isActive: false },
  { id: 2, username: "Crawford", isActive: true },
  { id: 3, username: "Grove", isActive: false },
  { id: 4, username: "Alfonso", isActive: true },
  { id: 5, username: "Catlaina", isActive: true },
  { id: 6, username: "Coralie", isActive: false },
  { id: 7, username: "Louis", isActive: false },
  { id: 8, username: "Nerti", isActive: true },
  { id: 9, username: "Elinor", isActive: true },
  { id: 10, username: "Gayle", isActive: false },
  { id: 11, username: "Laryssa", isActive: false },
  { id: 12, username: "Graham", isActive: false },
  { id: 13, username: "Marcello", isActive: false },
  { id: 14, username: "Caldwell", isActive: true },
  { id: 15, username: "Benoite", isActive: false },
  { id: 16, username: "Kathryne", isActive: false },
  { id: 17, username: "Benson", isActive: false },
  { id: 18, username: "Adrianne", isActive: false },
  { id: 19, username: "Cristionna", isActive: false },
  { id: 20, username: "Griff", isActive: false },
];
